"""add_history_table

Revision ID: 4ed8598ab954
Revises: 33655cc0e090
Create Date: 2026-03-01 04:00:24.758367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed8598ab954'
down_revision: Union[str, Sequence[str], None] = '33655cc0e090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=False, comment='Дата поступления письма'),
    sa.Column('status', sa.String(), nullable=False, comment='Статус обработки'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='ФИО отправителя'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email отправителя'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Контактный телефон'),
    sa.Column('company_object', sa.String(length=255), nullable=True, comment='Название предприятия или объекта'),
    sa.Column('device_type', sa.String(length=100), nullable=True, comment='Тип/модель прибора'),
    sa.Column('serial_numbers', sa.Text(), nullable=True, comment='Заводские номера приборов (можно несколько)'),
    sa.Column('original_text', sa.Text(), nullable=False, comment='Полный текст письма'),
    sa.Column('issue_summary', sa.Text(), nullable=True, comment='Краткое описание проблемы или запрос'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Категория вопроса (неисправность/калибровка/запрос документации)'),
    sa.Column('sentiment', sa.String(), nullable=True, comment='Эмоциональный окрас письма'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Уверенность модели в анализе'),
    sa.Column('extracted_entities', sa.JSON(), nullable=True, comment='Дополнительные сущности (номера заказов, даты и т.п.)'),
    sa.Column('generated_response', sa.Text(), nullable=True, comment='Сгенерированный AI ответ на основе базы знаний'),
    sa.Column('final_response', sa.Text(), nullable=True, comment='Итоговый ответ (после проверки/редактирования оператором)'),
    sa.Column('answered_at', sa.DateTime(), nullable=True, comment='Дата отправки ответа'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи в БД'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Время последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_history')
    op.drop_table('operators')
    # ### end Alembic commands ###
